services:
  api:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    container_name: classroom-api
    ports:
      - "3333:3333"
    volumes:
      - .:/app
      - /app/node_modules
    env_file: .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: classroom-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
